= ZephOS
:author: Vlad944467
:revdate: 2026-07-28
:lang: ru

image:https://img.shields.io/badge/OS-32--bit-blue.svg[32-bit]
image:https://img.shields.io/badge/lang-C-blue.svg[C]
image:https://img.shields.io/badge/license-GPLv3-green.svg[GPLv3]

**32-битная монолитная операционная система, написанная на C и Assembly**


== Возможности

* 32-битный защищённый режим
* Загрузка по стандарту Multiboot (GRUB/QEMU)
* Поддержка клавиатуры PS/2
* Текстовый режим VGA (80x25, 16 цветов)
* Звук через PC Speaker
* Запуск ELF программ
* Встроенные команды: `help`, `clear`, `reboot`, `echo`, `win`, `cat`, `fetch`, `run`
* ATA драйвер (чтение/запись секторов)
* Собственный шелл с историей команд
* Монолитное ядро


== Сборка и запуск

=== Ручная сборка

.Сборка загрузчика
[source,bash]
----
nasm -f elf32 boot/boot.asm -o boot.o
----

.Компиляция ядра
[source,bash]
----
gcc -m32 -ffreestanding -nostdlib -c kernel/kenel1.c -o kenel1.o
gcc -m32 -ffreestanding -nostdlib -c kernel/commands.c -o commands.o
gcc -m32 -ffreestanding -nostdlib -c kernel/read_keyboard.c -o read_keyboard.o
gcc -m32 -ffreestanding -nostdlib -c kernel/ata.c -o ata.o
gcc -m32 -ffreestanding -nostdlib -c kernel/video.c -o video.o
gcc -m32 -ffreestanding -nostdlib -c kernel/elf.c -o elf.o
----

.Линковка
[source,bash]
----
ld -m elf_i386 -T boot/linker.ld -o BitOS.elf boot.o kenel1.o commands.o read_keyboard.o ata.o video.o elf.o
----

=== Сборка через Makefile

[source,bash]
----
make
make clean
make rebuild
make run
----

=== Запуск в QEMU

[source,bash]
----
qemu-system-i386 -kernel ZephOS.elf
----

=== Запуск с диском (для ATA)

[source,bash]
----
qemu-system-i386 -kernel ZephOS.elf -hda fat16.img
----


== Структура проекта

[source,tree]
----
ZephOS/
├── boot/
│   ├── boot.asm          
│   └── linker.ld         
├── kernel/
│   ├── kenel1.c          # Ядро
│   ├── commands.c        # Команды шелла
│   ├── elf.c             # Загрузчик ELF
│   ├── read_keyboard.c   # PS/2 клавиатура
│   ├── ata.c             # ATA драйвер
│   └── video.c           # VGA вывод
├── grub/
│   └── grub.cfg         
├── docs/
│   └── COMMANDS.md       
├── images/
├── LICENSE.adoc 
├── Makefile
└── README.adoc
----


== Команды

=== Основные команды

[cols="1,3"]
|===
| Команда | Описание
| `help` | Показать справку
| `clear` | Очистить экран
| `reboot` | Перезагрузить систему
| `shutdown` | Выключить систему
| `echo` | Вывести текст
| `edit` | Текстовый редактор
| `notes` | Показать сохранённую заметку
| `save` | Сохранить заметку
| `load` | Загрузить заметку
| `bgcolor` | Сменить цвет фона
| `fetch` | Информация об ОС
| `run <сектор>` | Запустить ELF программу с диска
|===

=== Табличные команды (через `par`)

[cols="1,3"]
|===
| Команда | Описание
| `par help` | Справка по табличным командам
| `par hello` | Приветствие
| `par time` | Показать время
| `par calc` | Калькулятор (например: `par calc 2+3`)
| `par sleep` | Пауза
| `par bgcolor` | Сменить цвет фона
| `par edit` | Редактор
| `par clear` | Очистка экрана
| `par type` | Узнать тип команды
|===

=== Команда `run`

Загружает и запускает ELF-программу с диска.

[source,bash]
----
run 10
----

Программа должна быть скомпилирована статически для 32-bit x86 и записана в указанный сектор.

==== Компиляция программы

[source,bash]
----
gcc -static -m32 -nostdlib -fno-stack-protector -no-pie -Wl,-Ttext=0x100000 -o hello.elf hello.c
sudo dd if=hello.elf of=fat16.img bs=512 seek=10 conv=notrunc
----

==== Пример программы `hello.c`

[source,c]
----
void _start() {
    char *video = (char*)0xB8000;
    char *msg = "Hello from BitOS!";
    for (int i = 0; msg[i]; i++) {
        video[i * 2] = msg[i];
        video[i * 2 + 1] = 0x0F;
    }
    while (1);
}
----


== Зависимости

* `gcc` (с поддержкой `-m32`)
* `nasm`
* `ld`
* `qemu-system-x86` (для запуска)
* `make`

Для Ubuntu/Debian:

[source,bash]
----
sudo apt install gcc nasm qemu-system-x86 make
sudo apt install gcc-multilib
----


== Лицензия

*GNU General Public License v3.0*

Copyright (c) 2026 Vlad944467

Это свободное программное обеспечение.

**Можно:**
* Использовать, изменять и распространять код
* Использовать в коммерческих проектах

**Нельзя:**
* Закрывать код, если использовали этот

**Нужно:**
* Указывать автора
* Делиться изменениями под той же лицензией

Полный текст лицензии: https://www.gnu.org/licenses/gpl-3.0.html


== Автор

*Vlad944467*

GitHub: https://github.com/Vlad944467/ZephOS
